# Generated by Django 2.2.28 on 2023-07-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='status',
            new_name='state',
        ),
    ]
